#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application as ConsoleApp;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Output\OutputInterface;

use Caracal\Core\Application;
use Caracal\Core\Cache;
use Caracal\Core\Queue;

$app = Application::getInstance();
$console = new ConsoleApp('Caracal CLI', '1.0.0');

/*
|--------------------------------------------------------------------------
| SERVE COMMAND
|--------------------------------------------------------------------------
*/
$console->add(new class extends Command {
    protected function configure(): void {
        $this
            ->setName('serve')
            ->setDescription('Start development server')
            ->addOption('host', null, InputOption::VALUE_OPTIONAL, 'Host', '127.0.0.1')
            ->addOption('port', null, InputOption::VALUE_OPTIONAL, 'Port', '8000');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int {
        $host = $input->getOption('host');
        $port = $input->getOption('port');
        $output->writeln("<info>Starting Caracal dev server at http://{$host}:{$port}</info>");
        passthru("php -S {$host}:{$port} -t public");
        return Command::SUCCESS;
    }
});

/*
|--------------------------------------------------------------------------
| APP RUN
|--------------------------------------------------------------------------
*/
$console->add(new class extends Command {
    protected function configure(): void {
        $this->setName('app:run')->setDescription('Run application lifecycle');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int {
        $app = Application::getInstance();
        $app->run();
        $output->writeln('<info>Application lifecycle executed</info>');
        return Command::SUCCESS;
    }
});

/*
|--------------------------------------------------------------------------
| MIGRATE
|--------------------------------------------------------------------------
*/
$console->add(new class extends Command {
    protected function configure(): void {
        $this
            ->setName('migrate')
            ->setDescription('Run all database migrations')
            ->addOption('seed', null, InputOption::VALUE_NONE, 'Run seeders after migration');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int {
        $db = Application::getInstance()->db();
        if (!$db) {
            $output->writeln('<error>Database disabled or not configured</error>');
            return Command::FAILURE;
        }

        foreach (glob(__DIR__ . '/databases/migrations/*.php') as $file) {
            require_once $file;
            $class = basename($file, '.php');
            if (class_exists($class)) {
                (new $class)->up();
                $output->writeln("<info>Migrated:</info> $class");
            }
        }

        if ($input->getOption('seed')) {
            $seedCommand = $this->getApplication()->find('db:seed');
            $seedCommand->run($input, $output);
        }

        return Command::SUCCESS;
    }
});

/*
|--------------------------------------------------------------------------
| MIGRATE ROLLBACK
|--------------------------------------------------------------------------
*/
$console->add(new class extends Command {
    protected function configure(): void {
        $this->setName('migrate:rollback')->setDescription('Rollback last migration');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int {
        foreach (array_reverse(glob(__DIR__ . '/databases/migrations/*.php')) as $file) {
            require_once $file;
            $class = basename($file, '.php');
            if (class_exists($class)) {
                (new $class)->down();
                $output->writeln("<info>Rolled back:</info> $class");
                break;
            }
        }
        return Command::SUCCESS;
    }
});

/*
|--------------------------------------------------------------------------
| MIGRATE FRESH
|--------------------------------------------------------------------------
*/
$console->add(new class extends Command {
    protected function configure(): void {
        $this->setName('migrate:fresh')->setDescription('Reset DB & run all migrations');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int {
        foreach (array_reverse(glob(__DIR__ . '/databases/migrations/*.php')) as $file) {
            require_once $file;
            $class = basename($file, '.php');
            if (class_exists($class)) (new $class)->down();
        }
        $output->writeln('<info>Database reset complete</info>');

        $migrateCommand = $this->getApplication()->find('migrate');
        return $migrateCommand->run($input, $output);
    }
});

/*
|--------------------------------------------------------------------------
| SEED COMMAND
|--------------------------------------------------------------------------
*/
$console->add(new class extends Command {
    protected function configure(): void {
        $this
            ->setName('db:seed')
            ->setDescription('Run database seeders')
            ->addArgument('seeder', InputArgument::OPTIONAL, 'Specific seeder to run');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int {
        $seeder = $input->getArgument('seeder');
        if ($seeder) {
            $file = __DIR__ . '/databases/seeds/' . $seeder . '.php';
            if (file_exists($file)) {
                require_once $file;
                (new $seeder)->run();
                $output->writeln("<info>Seeded:</info> $seeder");
            } else {
                $output->writeln("<error>Seeder $seeder.php not found</error>");
            }
        } else {
            foreach (glob(__DIR__ . '/databases/seeds/*.php') as $file) {
                require_once $file;
                $class = basename($file, '.php');
                if (class_exists($class)) {
                    (new $class)->run();
                    $output->writeln("<info>Seeded:</info> $class");
                }
            }
        }
        return Command::SUCCESS;
    }
});

/*
|--------------------------------------------------------------------------
| CACHE SET
|--------------------------------------------------------------------------
*/
$console->add(new class extends Command {
    protected function configure(): void {
        $this
            ->setName('cache:set')
            ->setDescription('Set cache key/value')
            ->addOption('key', null, InputOption::VALUE_REQUIRED, 'Cache key')
            ->addOption('value', null, InputOption::VALUE_REQUIRED, 'Cache value')
            ->addOption('ttl', null, InputOption::VALUE_OPTIONAL, 'TTL seconds', 3600);
    }

    protected function execute(InputInterface $input, OutputInterface $output): int {
        $cache = Application::getInstance()->cache();
        $key   = $input->getOption('key');
        $value = $input->getOption('value');
        $ttl   = (int)$input->getOption('ttl');

        if (!$key || !$value) {
            $output->writeln('<error>--key and --value are required</error>');
            return Command::FAILURE;
        }

        $cache->set($key, $value, $ttl);
        $output->writeln("<info>Cache set:</info> $key = $value (TTL: $ttl s)");
        return Command::SUCCESS;
    }
});

/*
|--------------------------------------------------------------------------
| CACHE CLEAR
|--------------------------------------------------------------------------
*/
$console->add(new class extends Command {
    protected function configure(): void {
        $this->setName('cache:clear')->setDescription('Clear all cache');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int {
        $cache = Application::getInstance()->cache();
        $cache->clearAll();
        $output->writeln('<info>All cache cleared</info>');
        return Command::SUCCESS;
    }
});

$console->run();